// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package grpc.Service1;

public final class TempServiceImpl {
  private TempServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_maths_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_maths_NumberMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntemp.proto\022\005maths\"4\n\021CalculateResponse" +
      "\022\016\n\006result\030\001 \001(\002\022\017\n\007message\030\002 \001(\t\"\037\n\rNum" +
      "berMessage\022\016\n\006number\030\001 \001(\0022P\n\013TempServic" +
      "e\022A\n\013averageTemp\022\024.maths.NumberMessage\032\030" +
      ".maths.CalculateResponse\"\000(\001B\"\n\rgrpc.Ser" +
      "vice1B\017TempServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_maths_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_maths_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_maths_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_maths_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_maths_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
