// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water.proto

package grpc.service2;

public interface WaterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:water.WaterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
