// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: water.proto

package grpc.service2;

public interface WaterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:water.WaterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numbers = 1;</code>
   */
  int getNumbers();
}
