// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feed.proto

package grpc.service3;

public final class FeedServiceImpl {
  private FeedServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feed_FeedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feed_FeedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_feed_FeedResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_feed_FeedResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfeed.proto\022\004feed\"\035\n\013FeedMessage\022\016\n\006num" +
      "ber\030\001 \001(\005\"\036\n\014FeedResponse\022\016\n\006number\030\001 \001(" +
      "\0052K\n\013FeedService\022<\n\rfeedLivestock\022\021.feed" +
      ".FeedMessage\032\022.feed.FeedResponse\"\000(\0010\001B\"" +
      "\n\rgrpc.service3B\017FeedServiceImplP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_feed_FeedMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_feed_FeedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feed_FeedMessage_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_feed_FeedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_feed_FeedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_feed_FeedResponse_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
