// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feed.proto

package grpc.service3;

public interface FeedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:feed.FeedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
